baseURL = "https://goblindegook.com/"
languageCode = "en-gb"
title = "goblindegook"
theme = "goblindegook"
disableHugoGeneratorInject = true
pygmentsCodeFences = true

[permalinks]
  page = "/:filename"
  post = "/:year/:filename"

[params]
  author = "Luís Rodrigues"
  tagline = "Full of IT."
  description = "Luís Rodrigues writing about software development, design, and literature."
  intro = "My name is Luís Rodrigues and this site collects my writing.\n\nI'm [@goblindegook](https://twitter.com/goblindegook) on Twitter. Come by and say hello."
  disclaimer = "Opinions my own, unless borrowed."
  twitter = "@goblindegook"
  searchPrefill = "Search goblindegook"
  searchSite = "goblindegook.com"

[[menu.main]]
  name = "Home"
  identifier = "home"
  url = "/"
  weight = -100
