baseURL = "https://goblindegook.com/"
languageCode = "en-gb"
title = "goblindegook"
disableHugoGeneratorInject = true
pygmentsCodeFences = true
enableRobotsTXT = true

[permalinks]
  page      = "/:filename"
  post      = "/:year/:slug"
  til       = "/til/:year/:month/:day/:filename"
  echomatic = "/echomatic/:year/:month/:day/:filename"

[params]
  author = "Luís Rodrigues"
  tagline = "Full of IT."
  description = "Luís Rodrigues writing about software development, design, and literature."
  intro = "My name is Luís Rodrigues and this site collects my writing.\n\nI'm <a href=\"https://twitter.com/goblindegook\" rel=\"me\">@goblindegook</a> on Twitter. Come by and say hello."
  disclaimer = "Opinions my own, unless borrowed."
  twitter = "@goblindegook"
  searchPrefill = "Search goblindegook"
  searchSite = "goblindegook.com"
  mainSections = ["post", "til", "echomatic"]

[[menu.main]]
  name = "Home"
  identifier = "home"
  url = "/"
  weight = -100

[outputs]
  home = [ "HTML", "RSS" ]

[imaging]
  quality = 90

[mediaTypes]
  [mediaTypes."text/netlify"]
    suffixes = [""]
    delimiter = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = "node_modules/normalize.css/normalize.css"
    target = "assets/normalize.css"
  [[module.mounts]]
    source = "node_modules/css-modularscale/index.css"
    target = "assets/css-modularscale"
  [[module.mounts]]
    source = "node_modules/animate.css/animate.css"
    target = "assets/animate.css"
