[build]
  command = "yarn build"
  publish = "public"

[context.deploy-preview]
  command = "yarn build-preview"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.67.1"

[context.production.environment]
  HUGO_VERSION = "0.67.1"
