[build]
  command = "yarn && yarn build"
  publish = "public"

[context.deploy-preview]
  command = "yarn && yarn build:preview"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.76.5"

[context.production.environment]
  HUGO_VERSION = "0.76.5"
