[build]
  command = "yarn lint && yarn test run && yarn build"
  publish = "public"

[context.deploy-preview]
  command = "yarn lint && yarn test run && yarn build:preview"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.110.0"

[context.production.environment]
  HUGO_VERSION = "0.110.0"
