[build]
  command = "npm run lint && npm test run && npm run build"
  publish = "public"

[context.deploy-preview]
  command = "npm run lint && npm test run && npm run build:preview"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.152.2"

[context.production.environment]
  HUGO_VERSION = "0.152.2"
