[build]
  command = "./bun.sh && bun run lint && bun test && bun run build"
  publish = "public"

[context.deploy-preview]
  command = "./bun.sh && bun run lint && bun test && bun run build:preview"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.110.0"

[context.production.environment]
  HUGO_VERSION = "0.110.0"
