[build]
  command = "npm run build"
  publish = "public"

[context.deploy-preview]
  command = "npm run build-preview"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.29"

[context.production.environment]
  HUGO_VERSION = "0.29"
