name = "Goblindegook"
license = "MIT"
licenselink = "https://github.com/goblindegook/hugo-theme-goblindegook/blob/master/LICENSE.md"
description = ""
homepage = "https://goblindegook.com/"
tags = ["blog"]
features = ["responsive", "thumbnail", "grid", "syntax highlight", "structured data", "ogp", "twitter cards"]
min_version = "0.24.1"

[author]
  name = "Luís Rodrigues"
  homepage = "https://goblindegook.com"