backend:
  name: git-gateway
  branch: master

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/post"
    create: true
    slug: "{{slug}}/index"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string", default: "Luís Rodrigues"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Draft", name: "draft", widget: "number"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Featured Image"
        name: "image"
        widget: "object"
        fields:
        - {label: "Image", name: "src", widget: "image"}
        - {label: "Caption", name: "caption", widget: "string"}
        - {label: "Alternate Text", name: "alt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    folder: "content/page"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string", default: "Luís Rodrigues"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Draft", name: "draft", widget: "number"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Menu", name: "menu", widget: "string", default: "main"}
      - {label: "Body", name: "body", widget: "markdown"}
